[managers.system]
items = [
  "git",
  "zip",
  "lazygit-git",
  "unzip",
  "gcc",
  "wget",
  "fd",
  "grim",
  "slurp",
  "pavucontrol",
  "wl-clipboard",
  "dunst",
  "libnotify",
  "notification-daemon",
  "pass",
  "fzf",
  "pipewire",
  "wireplumber",
  "ntfs-3g",
  "os-prober",
]

