[managers.system]
items = [
  "git",
  "zip",
  "lazygit-git",
  "unzip",
  "gcc",
  "wget",
  "grim",
  "slurp",
  "maim",
  "nitrogen",
  "xclip",
  "nemo",
  "pavucontrol",
  "wl-clipboard",
  "dunst",
  "libnotify",
  "notification-daemon",
  "pipewire",
  "wireplumber",
  "pass",
  "xev",
]

